services:
  postgres-db:
    image: postgres:15-alpine
    container_name: bookreview-db
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=bookreview
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: