@baseUrl = http://localhost:8080
@prodUrl = https://bookreview-api-x5yd.onrender.com

### Register
POST {{prodUrl}}/api/auth/register
Content-Type: application/json

{
  "username": "tinhneee1",
  "email": "test2@gmail.com",
  "password": "12345678"
}


### Login
POST {{prodUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "tinhneee1",
  "password": "12345678"
}

> {%
    client.global.set("accessToken", response.body.token);
    // client.global.set("accessToken", "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNzc3MDg4NTg4LCJleHAiOjE3NzcxNzQ5ODh9.01FXT_L5CXlFafZI09JWbgRyPlfR0uN_iaCiMAgVZWY");

%}


### Get current user
GET {{prodUrl}}/api/users/me
Authorization: Bearer {{accessToken}}