@baseUrl = http://localhost:8080

### Register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "username": "tinhneee",
  "email": "test1@gmail.com",
  "password": "12345678"
}

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "tinhneee1",
  "password": "12345678"
}

> {%
    client.global.set("accessToken", response.body.token);

%}

### Get current user
GET {{baseUrl}}/api/users/me
Authorization: Bearer {{accessToken}}